development:
  adapter: postgresql
  encoding: unicode
  database: micro_learning_dev
  pool: 10
  username: dominicbett
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: micro_learning_test
  pool: 2
  username: dominicbett
  password:

production:
  adapter: postgresql
  encoding: unicode
  pool: 10
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
