require_relative('../app/models/category')
require_relative('../app/models/topic')

Category.create(name: 'programming')
programming = Category.find_by(name: 'programming')
hacking = Category.create(name: 'hacking')
hacking = Category.find_by(name: 'hacking')
philosophy = Category.create(name: 'philosophy')
philosophy = Category.find_by(name: 'philosophy')

Category.create(name: 'one')
Category.create(name: 'two')
Category.create(name: 'three')
Category.create(name: 'four')
Category.create(name: 'five')
Category.create(name: 'six')
Category.create(name: 'seven')
Category.create(name: 'eight')

programming.topics.create(name: 'ruby')
programming.topics.create(name: 'python')
programming.topics.create(name: 'java')
programming.topics.create(name: 'go')

hacking.topics.create(name: 'metaspoilt')
hacking.topics.create(name: 'ping')
hacking.topics.create(name: 'nmap')

philosophy.topics.create(name: 'evolution')
philosophy.topics.create(name: 'religion')
philosophy.topics.create(name: 'love')
